/**
 * Generate a downloadable booking receipt as a text file.
 * Uses plain text format for maximum compatibility (no PDF library needed).
 */

interface ReceiptData {
  bookingRef: string;
  clientName: string;
  providerName: string;
  service: string;
  date: string;
  time: string;
  duration: string;
  price: string;
  status: string;
}

export function generateReceipt(data: ReceiptData): string {
  const platformFee = "5%";
  const now = new Date().toLocaleString("en-ZA", { dateStyle: "long", timeStyle: "short" });

  return `
════════════════════════════════════════
         BION — Booking Receipt
════════════════════════════════════════

Booking Reference:  ${data.bookingRef}
Generated:          ${now}
Status:             ${data.status.toUpperCase()}

────────────────────────────────────────
CLIENT
────────────────────────────────────────
Name:               ${data.clientName}

────────────────────────────────────────
PROVIDER
────────────────────────────────────────
Name:               ${data.providerName}

────────────────────────────────────────
SESSION DETAILS
────────────────────────────────────────
Service:            ${data.service}
Date:               ${data.date}
Time:               ${data.time}
Duration:           ${data.duration}

────────────────────────────────────────
PAYMENT
────────────────────────────────────────
Session Price:      ${data.price}
Platform Fee:       ${platformFee}
Payment Method:     BIONWallet / Card

════════════════════════════════════════

BION (Pty) Ltd
Pretoria, South Africa
support@bionhealth.co.za
https://bionhealth.co.za

This receipt is generated by BION for your records.
For disputes, visit: bionhealth.co.za/legal/disputes

POPIA Notice: Your personal data is processed in
accordance with the Protection of Personal Information
Act. You may request data access or deletion at any
time from Settings → Privacy.

════════════════════════════════════════
`.trim();
}

export function downloadReceipt(data: ReceiptData): void {
  const text = generateReceipt(data);
  const blob = new Blob([text], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `BION-Receipt-${data.bookingRef}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}
